### ISSUE TITLE
Attach to PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [cooperative-computing-lab/coffea-wq-notebook#1]
Hi @btovar,

I noticed that you already minted a DOI for your talk/repository. That's great. I then just need that you attach the Zenodo entry to the pyhep2022 community (I will get a ping to curate from Zenodo) ... Can you do that?

While at it you can also update the title (the auto-generated one is ugly) and the conference related metadata "Meeting" as at for example https://zenodo.org/record/7075511#.YyyKdXZBxPY?

Many thanks,
Eduardo

**Comment by btovar** [comment]
Done!

**Comment by eduardo-rodrigues** [comment]
Thanks.
